// მანქანების ტურების მონაცემები
const carTours = [
    {
        id: 1,
        name: "თბილისის აღჭურვილი ჯიპების ტური",
        region: "tbilisi",
        carType: "suv",
        duration: "1 დღე",
        price: 120,
        pricePeriod: "ტურისთვის",
        description: "გაეცანით თბილისის ძირითად ღირსშესანიშნაობებს კომფორტული ჯიპით და პროფესიონალი ჰაიდგაიდით.",
        image: "/pages/addhome/tbilisi-jeep-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: true
    },
    {
        id: 2,
        name: "კახეთის ღვინის მარშრუტი პრემიუმ სედანით",
        region: "kakheti",
        carType: "premium",
        duration: "2 დღე",
        price: 350,
        pricePeriod: "ტურისთვის",
        description: "მოინახულეთ კახეთის საუკეთესო ღვინის მარანები პრემიუმ კლასის მანქანაში მარკირებული მარშრუტით.",
        image: "/pages/addhome/kakheti-premium-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: true
    },
    {
        id: 3,
        name: "სვანეთის სათავგადასავლო ჯიპ ტური",
        region: "svaneti",
        carType: "suv",
        duration: "5 დღე",
        price: 850,
        pricePeriod: "ტურისთვის",
        description: "გაემგზავრეთ სვანეთის მთებში 4x4 ჯიპებით. ნახეთ შუხელის კოშკები და ისიამოვნეთ ულამაზესი ხედებით.",
        image: "/pages/addhome/svaneti-jeep-tour.jpg",
        includesGuide: true,
        freeCancellation: false,
        popular: false
    },
    {
        id: 4,
        name: "აჭარის სანაპირო ტური კაბრიოლეტით",
        region: "adjara",
        carType: "convertible",
        duration: "3 დღე",
        price: 480,
        pricePeriod: "ტურისთვის",
        description: "ისიამოვნეთ შავი ზღვის სანაპიროს მარშრუტით ღია კაბრიოლეტში. ბათუმი, ქობულეთი, ურეკი და სხვა.",
        image: "/pages/addhome/adjara-convertible-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: true
    },
    {
        id: 5,
        name: "იმერეთის კულტურული ტური სედანით",
        region: "imereti",
        carType: "sedan",
        duration: "2 დღე",
        price: 220,
        pricePeriod: "ტურისთვის",
        description: "გაიცანით დასავლეთ საქართველოს კულტურული დედაქალაქი ქუთაისი და მისი შემოგარენი კომფორტული სედანით.",
        image: "/pages/addhome/imereti-sedan-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: false
    },
    {
        id: 6,
        name: "სამეგრელოს ოჯახური ტური მინივენით",
        region: "samegrelo",
        carType: "minivan",
        duration: "4 დღე",
        price: 600,
        pricePeriod: "ტურისთვის",
        description: "იდეალური ოჯახისთვის. მოინახულეთ ზუგდიდი, პოტი და სენაკი 8 ადგილიანი მინივენით.",
        image: "/pages/addhome/samegrelo-minivan-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: false
    },
    {
        id: 7,
        name: "რაჭის მთის ტური ჯიპებით",
        region: "racha",
        carType: "suv",
        duration: "3 დღე",
        price: 420,
        pricePeriod: "ტურისთვის",
        description: "აღმოაჩინეთ რაჭის დაუვიწყარი ლანდშაფტები და ცნობილი ხაშური და ამბროლაურის მხარეები.",
        image: "/pages/addhome/racha-jeep-tour.jpg",
        includesGuide: true,
        freeCancellation: false,
        popular: true
    },
    {
        id: 8,
        name: "მცხეთა-მთიანეთის ისტორიული ტური",
        region: "mtskheta-mtianeti",
        carType: "sedan",
        duration: "1 დღე",
        price: 90,
        pricePeriod: "ტურისთვის",
        description: "მოინახულეთ მცხეთა, ჯვრის მონასტერი და გუდაური კომფორტული სედანით და პროფესიონალი გიდით.",
        image: "/pages/addhome/mtskheta-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: false
    },
    {
        id: 9,
        name: "ქვემო ქართლის არქეოლოგიური ტური",
        region: "kvemo-kartli",
        carType: "suv",
        duration: "2 დღე",
        price: 280,
        pricePeriod: "ტურისთვის",
        description: "გაეცანით ქვემო ქართლის ისტორიულ და არქეოლოგიურ ძეგლებს დბელი და ბოლნისის მხარეში.",
        image: "/pages/addhome/kvemo-kartli-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: false
    },
    {
        id: 10,
        name: "გურიის ბუნების ტური",
        region: "guria",
        carType: "sedan",
        duration: "2 დღე",
        price: 190,
        pricePeriod: "ტურისთვის",
        description: "გაეცანით გურიის უნიკალურ ბუნებას და კულტურას. ოზურგეთი, ბახმარო, ნაწალში.",
        image: "/pages/addhome/guria-tour.jpg",
        includesGuide: true,
        freeCancellation: true,
        popular: false
    }
];